name: Suggestions
description: Suggest a change and/or feature
title: "feat: lorem ipsum dolor"
labels: ["suggestion", "feature"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill in this form to help us get a better understanding of your suggestion

  - type: textarea
    id: problem
    attributes:
      label: Your problem
      placeholder: e.g. this game doesn't have near enough rickrolls
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Your solution
      placeholder: e.g. make the game rickroll the player every 0.1 seconds
    validations:
      required: true