name: Question
description: How the heck do I _____??
title: "question: lorem ipsum dolor"
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill in this form so we can further help you with your question
  
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      placeholder: How do I rickroll someone with the mod
    validations:
      required: true
  
  - type: input
    id: mod-version
    attributes:
      label: CommentMentions version (optional)
      placeholder: v1.0-alpha.1

  - type: input
    id: loader-version
    attributes:
      label: Geode version (optional)
      placeholder: v5.0.0-alpha.1

  - type: input
    id: os-version
    attributes:
      label: OS version (optional)
      placeholder: iOS 26.0.1
  
  - type: checkboxes
    id: more-stuff
    attributes:
      label: Validations
      options:
        - label: I can confirm I've searched for similar questions and haven't found an answer to mine
          required: true